### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support

### ISSUE THREAD

**Issue by Chess321** [codedeliveryservice/Reckless#45]
### Feature description

It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by codedeliveryservice** [comment]
I don't believe there's a compiling problem here. Given that this same issue has been duplicated across over 70 repos, I'm closing this as spam. If you have compile logs that suggest otherwise, feel free to reopen the issue.
